# Generated by Django 2.1.7 on 2019-03-09 16:24

import PersonnelManagement.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='医生姓名')),
                ('gender', models.CharField(choices=[('man', '男'), ('woman', '女')], max_length=2, verbose_name='医生性别')),
                ('doctor_introduction', models.TextField(max_length=500, verbose_name='医生介绍')),
                ('avatar', models.ImageField(upload_to=PersonnelManagement.models.upload_to, verbose_name='医生头像')),
            ],
            options={
                'verbose_name': '医生信息管理',
                'verbose_name_plural': '医生信息管理',
            },
        ),
        migrations.CreateModel(
            name='PatientInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='用户名')),
                ('real_name', models.CharField(max_length=50, verbose_name='真实姓名')),
                ('id_card', models.CharField(max_length=18, verbose_name='身份证号码')),
                ('telphone', models.BigIntegerField(verbose_name='手机号码')),
                ('avatar', models.ImageField(upload_to=PersonnelManagement.models.upload_to, verbose_name='头像')),
            ],
            options={
                'verbose_name': '患者信息管理',
                'verbose_name_plural': '患者信息管理',
            },
        ),
    ]
