# Generated by Django 2.1.7 on 2019-03-16 14:28

import PersonnelManagement.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='医生姓名')),
                ('gender', models.CharField(choices=[('man', '男'), ('woman', '女')], max_length=10, verbose_name='医生性别')),
                ('doctor_introduction', models.TextField(max_length=500, verbose_name='医生介绍')),
                ('avatar', models.ImageField(upload_to=PersonnelManagement.models.upload_to, verbose_name='医生头像')),
            ],
            options={
                'verbose_name_plural': '医生信息管理',
                'verbose_name': '医生信息管理',
            },
        ),
        migrations.CreateModel(
            name='PatientInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=50, verbose_name='用户唯一标识')),
                ('session_key', models.CharField(max_length=50, verbose_name='会话秘钥')),
            ],
            options={
                'verbose_name_plural': '患者微信信息管理',
                'verbose_name': '患者微信信息管理',
            },
        ),
        migrations.CreateModel(
            name='VisitCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_name', models.CharField(max_length=50, verbose_name='真实姓名')),
                ('id_card', models.CharField(max_length=18, verbose_name='身份证号码')),
                ('id_type', models.CharField(max_length=5, verbose_name='身份证类型')),
                ('telphone', models.BigIntegerField(verbose_name='手机号码')),
            ],
            options={
                'verbose_name_plural': '就诊卡管理',
                'verbose_name': '就诊卡管理',
            },
        ),
        migrations.AddField(
            model_name='patientinformation',
            name='visit_card',
            field=models.ManyToManyField(blank=True, to='PersonnelManagement.VisitCard'),
        ),
    ]
