# Generated by Django 2.1.7 on 2019-03-10 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonnelManagement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientinformation',
            name='id_card',
        ),
        migrations.RemoveField(
            model_name='patientinformation',
            name='real_name',
        ),
        migrations.RemoveField(
            model_name='patientinformation',
            name='telphone',
        ),
        migrations.AlterField(
            model_name='doctorinformation',
            name='gender',
            field=models.CharField(choices=[('man', '男'), ('woman', '女')], max_length=10, verbose_name='医生性别'),
        ),
    ]
