# Generated by Django 2.1.7 on 2019-03-23 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonnelManagement', '0002_auto_20190322_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorinformation',
            name='gender',
            field=models.CharField(choices=[('主任医师', '主任医师'), ('副主任医师', '副主任医师'), ('主治医师', '主治医师'), ('医师', '医师')], max_length=30, verbose_name='医生职称'),
        ),
    ]
