# Generated by Django 2.1.7 on 2019-03-26 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonnelManagement', '0004_auto_20190323_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitcard',
            name='id_type',
            field=models.CharField(max_length=5, verbose_name='证件类型'),
        ),
    ]
