# Generated by Django 2.1.7 on 2019-04-15 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonnelManagement', '0005_auto_20190326_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientinformation',
            name='visit_card',
            field=models.ManyToManyField(blank=True, to='PersonnelManagement.VisitCard', verbose_name='绑定就诊卡'),
        ),
    ]
