# Generated by Django 2.1.7 on 2019-03-26 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='release_time',
            field=models.DateField(auto_now_add=True, verbose_name='发布时间'),
        ),
    ]
