# Generated by Django 2.1.7 on 2019-04-15 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0002_auto_20190326_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='introduction',
            field=models.TextField(default=1, max_length=500, verbose_name='新闻简介'),
            preserve_default=False,
        ),
    ]
