# Generated by Django 2.1.7 on 2019-03-09 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PersonnelManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='科室名称')),
            ],
            options={
                'verbose_name': '科室管理',
                'verbose_name_plural': '科室管理',
            },
        ),
        migrations.CreateModel(
            name='DepartmentClassification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='科室类别名称')),
            ],
            options={
                'verbose_name': '科室类别管理',
                'verbose_name_plural': '科室类别管理',
            },
        ),
        migrations.AddField(
            model_name='department',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HospitalBusiness.DepartmentClassification', verbose_name='所属科室类别'),
        ),
        migrations.AddField(
            model_name='department',
            name='doctors',
            field=models.ManyToManyField(to='PersonnelManagement.DoctorInformation', verbose_name='科室所属医生'),
        ),
    ]
