# Generated by Django 2.1.7 on 2019-03-10 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonnelManagement', '0002_auto_20190310_1541'),
        ('HospitalBusiness', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_name', models.CharField(max_length=50, verbose_name='真实姓名')),
                ('id_card', models.CharField(max_length=18, verbose_name='身份证号码')),
                ('telphone', models.BigIntegerField(verbose_name='手机号码')),
                ('user', models.ManyToManyField(to='PersonnelManagement.PatientInformation')),
            ],
            options={
                'verbose_name_plural': '就诊卡管理',
                'verbose_name': '就诊卡管理',
            },
        ),
    ]
