# Generated by Django 2.1.7 on 2019-03-23 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonnelManagement', '0002_auto_20190322_2324'),
        ('HospitalBusiness', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField(verbose_name='值班时间')),
                ('doctor_duty', models.ManyToManyField(to='PersonnelManagement.DoctorInformation', verbose_name='值班医生')),
            ],
            options={
                'verbose_name_plural': '值班管理',
                'verbose_name': '值班管理',
            },
        ),
    ]
