# Generated by Django 2.1.7 on 2019-03-23 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PersonnelManagement', '0004_auto_20190323_1600'),
        ('HospitalBusiness', '0002_shift'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_date', models.DateField(verbose_name='挂号时间')),
                ('submission_time', models.DateField(auto_now_add=True, verbose_name='提交时间')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HospitalBusiness.Department', verbose_name='所属科室')),
                ('doctors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PersonnelManagement.DoctorInformation', verbose_name='就诊医生')),
                ('visit_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PersonnelManagement.VisitCard', verbose_name='绑定就诊卡')),
                ('wx_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PersonnelManagement.PatientInformation', verbose_name='操作微信号')),
            ],
            options={
                'verbose_name': '挂号记录',
                'verbose_name_plural': '挂号记录',
            },
        ),
    ]
