# Generated by Django 2.1.7 on 2019-03-23 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalBusiness', '0003_registeredrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registeredrecord',
            name='wx_id',
        ),
    ]
