# Generated by Django 2.1.7 on 2019-03-26 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PersonnelManagement', '0005_auto_20190326_2058'),
        ('HospitalBusiness', '0004_remove_registeredrecord_wx_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '患者缴费管理',
                'verbose_name_plural': '患者缴费管理',
            },
        ),
        migrations.CreateModel(
            name='PaymentItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='项目名称')),
                ('price', models.FloatField(max_length=50, verbose_name='项目金额')),
            ],
            options={
                'verbose_name': '缴费项目管理',
                'verbose_name_plural': '缴费项目管理',
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_item',
            field=models.ManyToManyField(to='HospitalBusiness.PaymentItem'),
        ),
        migrations.AddField(
            model_name='payment',
            name='visit_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PersonnelManagement.VisitCard'),
        ),
    ]
