# Generated by Django 2.1.7 on 2019-03-28 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PersonnelManagement', '0005_auto_20190326_2058'),
        ('HospitalBusiness', '0005_auto_20190326_2058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_content', models.TextField(max_length=500, verbose_name='报告内容')),
                ('submission_time', models.DateField(auto_now_add=True, verbose_name='报告生成时间')),
                ('doctors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PersonnelManagement.DoctorInformation', verbose_name='就诊医生')),
                ('visit_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PersonnelManagement.VisitCard', verbose_name='患者就诊卡')),
            ],
            options={
                'verbose_name': '就诊报告管理',
                'verbose_name_plural': '就诊报告管理',
            },
        ),
        migrations.AlterField(
            model_name='payment',
            name='visit_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PersonnelManagement.VisitCard', verbose_name='患者就诊卡'),
        ),
    ]
