# Generated by Django 2.1.7 on 2019-04-15 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PersonnelManagement', '0006_auto_20190415_1100'),
        ('HospitalBusiness', '0006_auto_20190328_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorVisitsNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visits_time', models.DateField(verbose_name='当天值班时间')),
                ('visit_number', models.IntegerField(verbose_name='剩余就诊次数')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PersonnelManagement.DoctorInformation', verbose_name='医生名称')),
            ],
            options={
                'verbose_name_plural': '医生就诊次数管理',
                'verbose_name': '医生就诊次数管理',
            },
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_item',
            field=models.ManyToManyField(to='HospitalBusiness.PaymentItem', verbose_name='缴费项目'),
        ),
    ]
