# Generated by Django 2.1.7 on 2019-04-16 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalBusiness', '0008_auto_20190415_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorvisitsnumber',
            name='association_registered_record',
            field=models.ManyToManyField(blank=True, to='HospitalBusiness.RegisteredRecord', verbose_name='关联的挂号记录'),
        ),
    ]
